FROM nexus.ssf.sclzdev.net/ironbank/google/golang/golang-1.20:1.20.0 as builder
RUN mkdir -p /go/bin && \
    export GOPATH=~/go && \
    export PATH=$PATH:$GOPATH/bin && \
    export GO111MODULE=on && \
    export GOBIN=/go/bin && \
    chmod -R 777 /go && \
    go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.52.2

CMD [ "golangci-lint" ]